"""Shared helpers for the scripts that produce the numbers and figures of paper/v2."""
import argparse
import json
import os
import platform
import sys
import time
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

PAPER = ROOT / 'paper' / 'v2'


def parse_args(description):
    p = argparse.ArgumentParser(description=description)
    p.add_argument('--device', default='cuda' if torch.cuda.is_available() else 'cpu')
    p.add_argument('--mode', choices=['quick', 'full'], default='quick',
                   help='quick: minutes on a CPU; full: the sizes reported in the paper (GPU)')
    p.add_argument('--seed', type=int, default=0)
    p.add_argument('--out', default=str(PAPER / 'generated'), help='directory for generated .tex/.json')
    p.add_argument('--figdir', default=str(PAPER / 'figures'))
    args = p.parse_args()
    torch.manual_seed(args.seed)
    Path(args.out).mkdir(parents=True, exist_ok=True)
    Path(args.figdir).mkdir(parents=True, exist_ok=True)
    return args


def environment(device):
    info = {'torch': torch.__version__, 'python': platform.python_version(), 'device': str(device),
            'date': time.strftime('%Y-%m-%d')}
    if str(device).startswith('cuda'):
        info['gpu'] = torch.cuda.get_device_name(torch.device(device))
    else:
        info['cpu'] = platform.processor() or platform.machine()
        info['threads'] = torch.get_num_threads()
    return info


def save_json(args, name, payload):
    payload = dict(payload, environment=environment(args.device), mode=args.mode)
    with open(Path(args.out) / f'{name}.json', 'w') as f:
        json.dump(payload, f, indent=2, default=float)


def write_tex(args, name, text):
    with open(Path(args.out) / f'{name}.tex', 'w') as f:
        f.write('% generated by scripts/paper/*.py -- do not edit by hand\n' + text)


def env_macro(args, prefix):
    e = environment(args.device)
    hw = e.get('gpu') or f"CPU ({e.get('threads')} threads)"
    return (f"\\newcommand{{\\{prefix}Device}}{{{hw}}}\n"
            f"\\newcommand{{\\{prefix}Mode}}{{{args.mode}}}\n"
            f"\\newcommand{{\\{prefix}Torch}}{{{e['torch']}}}\n")


def sync(device):
    if str(device).startswith('cuda'):
        torch.cuda.synchronize()


def fmt(x, digits=4):
    return f"{x:.{digits}g}"


def sci(x, digits=2):
    if x == 0:
        return '0'
    m, e = f"{x:.{digits - 1}e}".split('e')
    return f"{m}\\times10^{{{int(e)}}}"
